branches:
  except:
    - gh-pages
sudo: false
addons:
  apt:
    packages:
      - libhunspell-1.3-0
      - hunspell-en-us
      - libhunspell-dev
      - myspell-es
language: perl
perl:
  - "5.16"
before_install:
  - cpanm -n Alien::Hunspell
script: "perl Makefile.PL && make disttest"
